{"cells":[{"cell_type":"markdown","metadata":{"id":"pstlzKwZ2F1l"},"source":["#Import and Initial Mount Disk\n"]},{"cell_type":"code","execution_count":7,"metadata":{"executionInfo":{"elapsed":9,"status":"aborted","timestamp":1677772044658,"user":{"displayName":"Vũ Đức Lâm Nguyễn","userId":"05507541945691209538"},"user_tz":-420},"id":"cflxDTZEGl_F"},"outputs":[],"source":["# install library\n","# !pip install -U tensorflow-addons\n","# !pip install facenet-pytorch\n"]},{"cell_type":"code","execution_count":8,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":391},"executionInfo":{"elapsed":7288,"status":"error","timestamp":1677772070909,"user":{"displayName":"Vũ Đức Lâm Nguyễn","userId":"05507541945691209538"},"user_tz":-420},"id":"11TpHNGi2BRj","outputId":"d4e88ae7-d4aa-4d01-a0d2-9f83589b21a4"},"outputs":[],"source":["import os\n","# Mount drive\n","# from google.colab import drive\n","# drive.mount(\"/content/drive\")\n","# path = \"/content/drive/My Drive/Colab Notebooks/face_recognize\"\n","# os.chdir(path)\n","\n","import time\n","import tensorflow_addons as tfa\n","import tensorflow as tf\n","from tensorflow.keras import models, layers, metrics, optimizers, Model\n","from tensorflow.keras.layers import Input, Dense, BatchNormalization\n","from functools import partial\n","import matplotlib.pyplot as plt\n","import numpy as np\n","import cv2\n","import math\n","import io\n","import pickle\n","import tensorflow_datasets as tfds\n","import random\n","import csv\n","\n","from train_tensorflow.inceptionresnetv1 import InceptionResNetV1\n","from train_tensorflow.models import convert_model_to_embedding,\\\n","    LayerBeforeArcFace, ArcFaceLoss, \\\n","    call_instance_model, call_instance_model_old, convert_dense_layer_to_arcface,\\\n","    special_convert_dense_layer_to_arcface\n","from train_tensorflow.Classify import Classify\n","from tool.FormatFunction import FormatFunction\n","from tool.FileFunction import FileFunction\n","from tool.GlobalValue import GlobalValue\n"]},{"cell_type":"code","execution_count":9,"metadata":{"id":"tw5icW__ANcX","outputId":"a8638ee7-6653-4999-babe-7e3f29a668b4"},"outputs":[{"name":"stdout","output_type":"stream","text":["Num GPUs Available:  1\n"]}],"source":["print(\"Num GPUs Available: \", len(tf.config.list_physical_devices('GPU')))\n"]},{"cell_type":"markdown","metadata":{"id":"arWBdNC42LO8"},"source":["# Train"]},{"cell_type":"markdown","metadata":{"id":"cLa5A6udvGwZ"},"source":["## Init value"]},{"cell_type":"code","execution_count":10,"metadata":{"id":"-EpkTrUkvL8-"},"outputs":[],"source":["READ_RAW_DATA_THEN_SAVE = False\n","backbone_type = \"InceptionResNetV2Old\"\n","head_type = \"Dense\"\n","MODEL_NAME = f\"160-64-{backbone_type}-{head_type}(v1)\"\n","is_convert = False\n","path_save_model = os.path.join(os.getcwd(), \"save_model\", MODEL_NAME)\n","global_value = GlobalValue(image_size=[160, 260], batch_size=64, shuffle_size=1000, ratio_train=0.9, ratio_test=0.1, ratio_valid=0.0, epochs=40, small_epochs=50,\n","                           image_each_class=15)\n","format_function = FormatFunction(global_value)\n","file_function = FileFunction()\n"]},{"cell_type":"markdown","metadata":{"id":"CNrrqpjynVoz"},"source":["## Prepare folder and other thing"]},{"cell_type":"code","execution_count":11,"metadata":{"id":"5pAdqjPenT23"},"outputs":[],"source":["# Create folder to save model\n","if not os.path.exists(path_save_model):\n","    os.makedirs(path_save_model)\n","\n","# Read label dictionary(name of people not the path of image)\n","if READ_RAW_DATA_THEN_SAVE:\n","    label_dict = dict()\n","    label_dict.update(format_function.get_label_dict(\n","        os.path.join(os.getcwd(), \"dataset\", \"CASIA_align\")))\n","    label_dict.update(format_function.get_label_dict(\n","        os.path.join(os.getcwd(), \"dataset\", \"AFDB\")))\n","    path = os.path.join(os.getcwd(), \"cache\", \"data\", \"label_dict.pkl\")\n","    with open(path, 'wb') as file:\n","        pickle.dump(label_dict, file)\n","path = os.path.join(os.getcwd(), \"cache\", \"data\", \"label_dict.pkl\")\n","with open(path, 'rb') as f:\n","    label_dict = pickle.load(f)\n","\n","# Save data path to file to read faster\n","if READ_RAW_DATA_THEN_SAVE:\n","    path_image_no_mask = list()\n","    path_image_no_mask.extend(file_function.get_data_path_by_dictionary(\n","        os.path.join(os.getcwd(), \"dataset\", \"CASIA_align\")))\n","    path_image_no_mask.extend(file_function.get_data_path_by_dictionary(\n","        os.path.join(os.getcwd(), \"dataset\", \"AFDB\")))\n","    saved_path = os.path.join(os.getcwd(), \"cache\",\n","                              \"data\", \"path_image_no_mask.pkl\")\n","    with open(saved_path, 'wb') as file:\n","        pickle.dump(path_image_no_mask, file)\n","\n","    path_image_mask = list()\n","    path_image_mask.extend(file_function.get_data_path_by_dictionary(\n","        os.path.join(os.getcwd(), \"dataset\", \"CASIA_mask\")))\n","    path_image_mask.extend(file_function.get_data_path_by_dictionary(\n","        os.path.join(os.getcwd(), \"dataset\", \"AFDB_mask\")))\n","    saved_path = os.path.join(os.getcwd(), \"cache\",\n","                              \"data\", \"path_image_mask.pkl\")\n","    with open(saved_path, 'wb') as file:\n","        pickle.dump(path_image_mask, file)\n"]},{"cell_type":"markdown","metadata":{"id":"7Dz4PftxE6XC"},"source":["## Start train"]},{"attachments":{},"cell_type":"markdown","metadata":{"id":"lZpKIQAUTDpm"},"source":["# Train version 1\n"]},{"cell_type":"code","execution_count":12,"metadata":{"id":"0Qwp3pemj3zi","outputId":"499b5200-25bc-42a9-fcb5-b7ea3f57ee10"},"outputs":[{"name":"stdout","output_type":"stream","text":["load  g:\\My Drive\\Colab Notebooks\\face_recognize\\save_model\\160-64-InceptionResNetV2Old-Dense(v1)\\epoch34.h5\n","--------------------------big epoch 35--------------------------\n"]},{"ename":"ResourceExhaustedError","evalue":"Graph execution error:\n\nDetected at node 'InceptionResNetV2Old/batch_normalization_205/FusedBatchNormV3' defined at (most recent call last):\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\traitlets\\config\\application.py\", line 1041, in launch_instance\n      app.start()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 724, in start\n      self.io_loop.start()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n      handle._run()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 512, in dispatch_queue\n      await self.process_one()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 501, in process_one\n      await dispatch(*args)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 408, in dispatch_shell\n      await result\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 731, in execute_request\n      reply_content = await reply_content\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 417, in do_execute\n      res = shell.run_cell(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n      result = self._run_cell(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n      return runner(coro)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\nguye\\AppData\\Local\\Temp\\ipykernel_38876\\3380202306.py\", line 103, in <module>\n      history = model.fit(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n      return step_function(self, iterator)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n      outputs = model.train_step(data)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n      y_pred = self(x, training=True)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\layers\\normalization\\batch_normalization.py\", line 850, in call\n      outputs = self._fused_batch_norm(inputs, training=training)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\layers\\normalization\\batch_normalization.py\", line 660, in _fused_batch_norm\n      output, mean, variance = control_flow_util.smart_cond(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\control_flow_util.py\", line 108, in smart_cond\n      return tf.__internal__.smart_cond.smart_cond(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\layers\\normalization\\batch_normalization.py\", line 634, in _fused_batch_norm_training\n      return tf.compat.v1.nn.fused_batch_norm(\nNode: 'InceptionResNetV2Old/batch_normalization_205/FusedBatchNormV3'\nOOM when allocating tensor with shape[64,64,77,127] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node InceptionResNetV2Old/batch_normalization_205/FusedBatchNormV3}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_74862]","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mResourceExhaustedError\u001b[0m                    Traceback (most recent call last)","Cell \u001b[1;32mIn[12], line 103\u001b[0m\n\u001b[0;32m     99\u001b[0m test_dataset \u001b[39m=\u001b[39m test_dataset\u001b[39m.\u001b[39mprefetch(\n\u001b[0;32m    100\u001b[0m     buffer_size\u001b[39m=\u001b[39mtf\u001b[39m.\u001b[39mdata\u001b[39m.\u001b[39mexperimental\u001b[39m.\u001b[39mAUTOTUNE)\n\u001b[0;32m    102\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39m--------------------------big epoch \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m--------------------------\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(actual_epochs))\n\u001b[1;32m--> 103\u001b[0m history \u001b[39m=\u001b[39m model\u001b[39m.\u001b[39;49mfit(\n\u001b[0;32m    104\u001b[0m     train_dataset,\n\u001b[0;32m    105\u001b[0m     epochs\u001b[39m=\u001b[39;49m\u001b[39m1\u001b[39;49m,\n\u001b[0;32m    106\u001b[0m     validation_data\u001b[39m=\u001b[39;49mtest_dataset\n\u001b[0;32m    107\u001b[0m )\n\u001b[0;32m    108\u001b[0m model\u001b[39m.\u001b[39msave_weights(os\u001b[39m.\u001b[39mpath\u001b[39m.\u001b[39mjoin(\n\u001b[0;32m    109\u001b[0m     path_save_model, \u001b[39m\"\u001b[39m\u001b[39mepoch\u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m.h5\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(actual_epochs)))\n\u001b[0;32m    110\u001b[0m \u001b[39mwith\u001b[39;00m \u001b[39mopen\u001b[39m(os\u001b[39m.\u001b[39mpath\u001b[39m.\u001b[39mjoin(os\u001b[39m.\u001b[39mgetcwd(), \u001b[39m\"\u001b[39m\u001b[39mcache\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39mlog\u001b[39m\u001b[39m\"\u001b[39m, MODEL_NAME\u001b[39m+\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m.csv\u001b[39m\u001b[39m\"\u001b[39m), \u001b[39m\"\u001b[39m\u001b[39ma\u001b[39m\u001b[39m\"\u001b[39m, newline\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39m'\u001b[39m) \u001b[39mas\u001b[39;00m f:\n","File \u001b[1;32mc:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[0;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[1;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[0;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n","File \u001b[1;32mc:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py:54\u001b[0m, in \u001b[0;36mquick_execute\u001b[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[0;32m     52\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     53\u001b[0m   ctx\u001b[39m.\u001b[39mensure_initialized()\n\u001b[1;32m---> 54\u001b[0m   tensors \u001b[39m=\u001b[39m pywrap_tfe\u001b[39m.\u001b[39mTFE_Py_Execute(ctx\u001b[39m.\u001b[39m_handle, device_name, op_name,\n\u001b[0;32m     55\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[0;32m     56\u001b[0m \u001b[39mexcept\u001b[39;00m core\u001b[39m.\u001b[39m_NotOkStatusException \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m     57\u001b[0m   \u001b[39mif\u001b[39;00m name \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n","\u001b[1;31mResourceExhaustedError\u001b[0m: Graph execution error:\n\nDetected at node 'InceptionResNetV2Old/batch_normalization_205/FusedBatchNormV3' defined at (most recent call last):\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\traitlets\\config\\application.py\", line 1041, in launch_instance\n      app.start()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 724, in start\n      self.io_loop.start()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n      handle._run()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 512, in dispatch_queue\n      await self.process_one()\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 501, in process_one\n      await dispatch(*args)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 408, in dispatch_shell\n      await result\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 731, in execute_request\n      reply_content = await reply_content\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 417, in do_execute\n      res = shell.run_cell(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n      result = self._run_cell(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n      return runner(coro)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\nguye\\AppData\\Local\\Temp\\ipykernel_38876\\3380202306.py\", line 103, in <module>\n      history = model.fit(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n      return step_function(self, iterator)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n      outputs = model.train_step(data)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n      y_pred = self(x, training=True)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\layers\\normalization\\batch_normalization.py\", line 850, in call\n      outputs = self._fused_batch_norm(inputs, training=training)\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\layers\\normalization\\batch_normalization.py\", line 660, in _fused_batch_norm\n      output, mean, variance = control_flow_util.smart_cond(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\utils\\control_flow_util.py\", line 108, in smart_cond\n      return tf.__internal__.smart_cond.smart_cond(\n    File \"c:\\Users\\nguye\\Anaconda3\\envs\\python310\\lib\\site-packages\\keras\\layers\\normalization\\batch_normalization.py\", line 634, in _fused_batch_norm_training\n      return tf.compat.v1.nn.fused_batch_norm(\nNode: 'InceptionResNetV2Old/batch_normalization_205/FusedBatchNormV3'\nOOM when allocating tensor with shape[64,64,77,127] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node InceptionResNetV2Old/batch_normalization_205/FusedBatchNormV3}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_74862]"]}],"source":["# Create embedding model\n","# tf.config.run_functions_eagerly(True)\n","input_shape = (global_value.IMAGE_SIZE[0], global_value.IMAGE_SIZE[1], 3)\n","input = Input(shape=input_shape)\n","model = call_instance_model_old(input_shape, num_classes=len(label_dict), embd_shape=512, head_type=head_type,\n","                            backbone_type=backbone_type)\n","# ----find the latest epoch\n","actual_epochs = 1\n","if is_convert:\n","    path_dense = os.path.join(os.getcwd(), \"save_model\", \"160-64-InceptionResNetV1-Dense(v1)\",\n","                              \"epoch35.h5\")\n","    model = special_convert_dense_layer_to_arcface(path_dense, input_shape,\n","                                                   len(label_dict), 512, model_name=model_name)\n","else:\n","    # ----find the latest epoch\n","    for i in range(1000):\n","        last_save_path = os.path.join(\n","            path_save_model, \"epoch{}.h5\".format(actual_epochs))\n","        if not os.path.exists(last_save_path):\n","            break\n","        actual_epochs += 1\n","\n","    # Load saved model\n","    if (actual_epochs != 1):\n","        load_path = os.path.join(\n","            path_save_model, \"epoch{}.h5\".format(actual_epochs-1))\n","        print(\"load \", load_path)\n","        model.load_weights(load_path)\n","\n","if head_type == 'ArcFace':\n","    loss_function = ArcFaceLoss(scale=30)\n","elif head_type == \"Dense\":\n","    loss_function = tf.keras.losses.SparseCategoricalCrossentropy(\n","        from_logits=True)\n","model.compile(\n","    optimizer=tf.keras.optimizers.Adam(0.001),\n","    loss=loss_function,\n","    metrics=[tf.keras.metrics.SparseCategoricalAccuracy()]\n",")\n","# model.summary()\n","# tf.keras.utils.plot_model(model, to_file=\"model.png\", show_shapes=True)\n","\n","# Normal train network\n","for i in range(global_value.EPOCHS):\n","    # Measure time\n","    now = time.time()\n","    # Read data path from file\n","    path = os.path.join(os.getcwd(), \"cache\", \"data\", \"path_image_no_mask.pkl\")\n","    with open(path, 'rb') as f:\n","        path_image_no_mask = pickle.load(f)\n","        path_image_no_mask = file_function.get_data_path_with_limit(\n","            path_image_no_mask, global_value.IMAGE_EACH_CLASS)\n","    path = os.path.join(os.getcwd(), \"cache\", \"data\", \"path_image_mask.pkl\")\n","    with open(path, 'rb') as f:\n","        path_image_mask = pickle.load(f)\n","        path_image_mask = file_function.get_data_path_with_limit(\n","            path_image_mask, global_value.IMAGE_EACH_CLASS)\n","\n","    # Combine data path\n","    path_image_no_mask.extend(path_image_mask)\n","    random.shuffle(path_image_no_mask)\n","\n","    # Index label (change label of data from string to number)\n","    label_index = list()\n","    for path in path_image_no_mask:\n","        label = path.split(os.sep)[-2]\n","        label = label_dict[label]\n","        label_index.append(label)\n","    path_dataset = tf.data.Dataset.from_tensor_slices(path_image_no_mask)\n","    label_dataset = tf.data.Dataset.from_tensor_slices(label_index)\n","    origin_dataset = tf.data.Dataset.zip((path_dataset, label_dataset))\n","\n","    # Repeat data\n","    # origin_dataset  = origin_dataset.shuffle(global_value.SHUFFLE_SIZE).repeat(2)\n","\n","    # Split train, test datase\n","    train_dataset, test_dataset, _ = format_function.get_dataset_partition(\n","        origin_dataset, 0.9, 0.1, 0)\n","\n","    # read data from path\n","    train_dataset = train_dataset.map(\n","        format_function.process_image, num_parallel_calls=tf.data.AUTOTUNE)\n","    test_dataset = test_dataset.map(\n","        format_function.process_image, num_parallel_calls=tf.data.AUTOTUNE)\n","\n","    # augmentation data(flip, rotate,...)\n","    train_dataset = train_dataset.map(\n","        format_function.augment_data, num_parallel_calls=tf.data.AUTOTUNE)\n","    test_dataset = test_dataset.map(\n","        format_function.augment_data, num_parallel_calls=tf.data.AUTOTUNE)\n","\n","    # batch data\n","    train_dataset = train_dataset.batch(global_value.BATCH_SIZE)\n","    test_dataset = test_dataset.batch(global_value.BATCH_SIZE)\n","\n","    # Set cache and prefetch to improve performance\n","    train_dataset = train_dataset.prefetch(\n","        buffer_size=tf.data.experimental.AUTOTUNE)\n","    test_dataset = test_dataset.prefetch(\n","        buffer_size=tf.data.experimental.AUTOTUNE)\n","\n","    print(\"--------------------------big epoch {}--------------------------\".format(actual_epochs))\n","    history = model.fit(\n","        train_dataset,\n","        epochs=1,\n","        validation_data=test_dataset\n","    )\n","    model.save_weights(os.path.join(\n","        path_save_model, \"epoch{}.h5\".format(actual_epochs)))\n","    with open(os.path.join(os.getcwd(), \"cache\", \"log\", MODEL_NAME+\".csv\"), \"a\", newline='') as f:\n","        row = [actual_epochs, history.history['loss'], history.history['sparse_categorical_accuracy'],\n","               history.history['val_loss'], history.history['val_sparse_categorical_accuracy'], time.time() - now]\n","        writer = csv.writer(f)\n","        writer.writerow(row)\n","    actual_epochs += 1\n","    # https://stackoverflow.com/questions/64734474/how-to-calculate-accuracy-for-facial-recognition-system\n"]}],"metadata":{"colab":{"machine_shape":"hm","provenance":[]},"gpuClass":"premium","kernelspec":{"display_name":"python310","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.8"},"vscode":{"interpreter":{"hash":"1089d176cd5639e770617b9490c2e07484c91636366b75c75a40730f35025e37"}}},"nbformat":4,"nbformat_minor":0}
